### ISSUE TITLE
CSS aus Child-Theme wird nicht angewendet

### ISSUE THREAD

**Issue by Deku86** [inpsyde/hamburg-child-starter#8]
Durch die Abfrage des Farbschemas (functions.php Zeile 46/47) wird bei Verwendung eines anderen Farbschemas verhindert, das die CSS-Anpassungen im Child-Theme greifen. Die Dateien werden dadurch nicht mehr geladen. 
Diese Zeilen müssten also entfallen:
```php
if ( 'pink' !== get_theme_mod( 'color_scheme' ) )
  return NULL;
```

**Comment by bueltge** [comment]
In der Funktion wird lediglich das Pink stylesheet geladen, wenn das nicht aktiv ist, dann macht der Rest in der Funktion keinen Sinn, daher raus. Wenn andere styles aktiviert werden, muss der default kommen, da sollte nochmal hingeschaut werden.

**Comment by glueckpress** [comment]
Duplicates https://github.com/inpsyde/hamburg-child-starter/issues/7
