### ISSUE TITLE
Sprachdatei im Child-Theme lädt nicht 

### ISSUE THREAD

**Issue by twern** [inpsyde/hamburg-child-starter#9]
Die Zeile ist Fehlerhaft https://github.com/inpsyde/hamburg-child-starter/blob/master/functions.php#L26 und greift damit nicht auf die Sprachdatei im Child-Theme zu.

Änderung müsste erfolgen von  <em>theme_hamburg_child_textdomain</em> in <em>theme_hamburg_textdomain</em>.

**Comment by glueckpress** [comment]
Die Zeile definiert eine neue Textdomain `theme_hamburg_child_textdomain` und lädt für diese Textdomain etwaige Child-Theme-Sprachdateien aus dem Ordner _languages_ des Child-Themes, so dieser und die entsprechenden Sprachdateien vorhanden sind. 

Gedacht ist die beispielhafte Registrierung der eigenen Textdomain für eigene Strings im Child-Theme, separat von der Textdomain des Eltern-Themes.
